# Generated by Django 4.1.1 on 2022-10-04 22:04

import ckeditor.fields
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_doors_alter_car_fuel_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Cruise Control', 'Cruise Control'), ('Audio Interface', 'Audio Interface'), ('Airbags', 'Airbags'), ('Air Conditioning', 'Air Conditioning'), ('Seat Heating', 'Seat Heating'), ('Alarm System', 'Alarm System'), ('ParkAssist', 'ParkAssist'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Wind Deflector', 'Wind Deflector'), ('Bluetooth Handset', 'Bluetooth Handset')], max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('AN', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('GO', 'Goa'), ('BI', 'Bihar'), ('CH', 'Chhattisgarh'), ('GU', 'Gujarat'), ('KO', 'Haryana'), ('SU', 'Himachal Pradesh'), ('JA', 'Jharkhand'), ('LA', 'Karnataka'), ('KA', 'Kerala'), ('NA', 'Madhya Pradesh'), ('IN', 'Maharashtra'), ('TH', 'Manipur'), ('BH', 'Meghalaya'), ('VI', 'Mizoram'), ('PA', 'Nagaland'), ('VA', 'Odisha'), ('GH', 'Punjab'), ('LU', 'Rajasthan'), ('AG', 'Sikkim'), ('NA', 'Tamil Nadu'), ('FA', 'Telangana'), ('ME', 'Tripura'), ('RA', 'Uttar Pradesh'), ('VA', 'Uttarakhand'), ('SR', 'West Bengal'), ('AU', 'Andaman and Nicobar Islands'), ('DH', 'Chandigarh'), ('NM', 'Dadra & Nagar Haveli'), ('AM', 'Delhi'), ('AL', 'Jammu and Kashmir'), ('RA', 'Lakshadweep'), ('CO', 'Puducherry'), ('JA', 'Ladakh')], max_length=100),
        ),
    ]
